### ISSUE TITLE
using knitr, cowplot not printing if a plot exists in the RSTUDIO GUI

### ISSUE THREAD

**Issue by Courvoisier13** [wilkelab/cowplot#51] opened 2016-11-14 17:24 UTC
Hi,
I am using RSTUDIO and knitr. I use cowplot to put graphs in a custom grid. If a plot is present in the RSTUDIO UI, then not plot shows in the produced pdf. If I erase the plots (effectively using dev.off()) then the plots are now knitted.
Doing the grid manually, using grid, does not have the same issue. I like cowplot's clarity though. good job

Is this is related to https://github.com/wilkelab/cowplot/issues/24?

Thanks

```
sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252    LC_MONETARY=English_United Kingdom.1252
[4] LC_NUMERIC=C                            LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] grid      stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] ggrepel_0.6.3   plotly_4.5.6    cowplot_0.7.0   shiny_0.14.2    xtable_1.8-2    readxl_0.1.1    tidyr_0.6.0     stringr_1.1.0   dplyr_0.5.0    
[10] lubridate_1.6.0 gridExtra_2.2.1 reshape2_1.4.2  scales_0.4.1    ggplot2_2.2.0   knitr_1.15     

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.7        magrittr_1.5       munsell_0.4.3      viridisLite_0.1.3  colorspace_1.3-0   R6_2.2.0           httr_1.2.1        
 [8] plyr_1.8.4         tools_3.3.2        gtable_0.2.0       DBI_0.5-1          htmltools_0.3.5    lazyeval_0.2.0     assertthat_0.1    
[15] digest_0.6.10      tibble_1.2         purrr_0.2.2        RColorBrewer_1.1-2 htmlwidgets_0.8    base64enc_0.1-3    evaluate_0.10     
[22] mime_0.5           labeling_0.3       stringi_1.1.2      jsonlite_1.1       httpuv_1.3.3      
```

**Comment by clauswilke** [comment] 2016-11-14 17:35
Could you post a minimal file that I can use to reproduce the issue?

**Comment by Courvoisier13** [comment] 2016-11-29 12:23
Hi sorry for the delay:
Update:
here is the .Rnw file:
```
\documentclass{article}
\begin{document}
\begin{center}
<<echo=FALSE, out.width='1\\linewidth', fig.width=15, fig.height=17, warning=FALSE, message=FALSE >>=
if(T){
	library(cowplot)
	p = ggplot(pressure, aes(temperature, pressure)) + geom_line()
	p_1 = plot_grid(p, p, labels = c("A", "B"))
	p_2 = plot_grid(p, p, labels = c("A", "B"))
	plot_grid(p_1, p_2, ncol = 1)
}
@
\end{center}
\end{document}
```

1. Step 1: I source the file in Rstudio. The image appears in the UI.
2. Step 2: 

- Option 1: If I use the "Compile pdf" button in Rstudio then I have no problem. The pdf has the figure.
- Option 2: I use the following code and compile it. 
```
library(knitr)
compiler = "xelatex"
outTex = "test2.tex"
outPdf = "test2.pdf"
src = "test2.Rnw"
outTexFile = knit(src, output = outTex, quiet = T)
Sys.setenv(PDFLATEX = compiler)
buff = tools::texi2pdf(file = outTexFile, clean = T)
```

Then the pdf comes out empty with no graph. If I clear all graphs from the Rstudio GUI. Then the plot appears in the pdf.

- Option 3: It looks like if I add a # to the end of the chunk where the plot is being produced solves the problem. How weird. I've had this issue for a long time and I just found this out:


```
\documentclass{article}
\begin{document}
\begin{center}
<<echo=FALSE, out.width='1\\linewidth', fig.width=15, fig.height=17, warning=FALSE, message=FALSE >>=
if(T){
	library(cowplot)
	p = ggplot(pressure, aes(temperature, pressure)) + geom_line()
	p_1 = plot_grid(p, p, labels = c("A", "B"))
	p_2 = plot_grid(p, p, labels = c("A", "B"))
	plot_grid(p_1, p_2, ncol = 1)
}
#
@
\end{center}

\end{document}
```

**Comment by clauswilke** [comment] 2016-11-29 16:26
And if you use ggplot2 instead of cowplot all this works as expected?

**Comment by Courvoisier13** [comment] 2016-12-04 16:42
yes, this works fine.

**Comment by AliciaSchep** [comment] 2017-11-10 01:56
I have also observed this issue, when making an html_document from Rmd file.  Non-cowplot ggplot2 plots show up, but not the cowplot ones.  They do show up if I clear the plot console in Rstudio, or if knitting using the knit button on rstudio, but do not show up if using rmarkdown::render and the plot device on rstudio is open.  I can put together a minimal example with Rmd if that would be helpful in addition to the Rnw example above.

**Comment by clauswilke** [comment] 2017-11-11 05:44
Alicia,

yes, I'm aware. I blame the R Studio graphics device. It doesn't reliably work with the `ggplot2::ggplotGrob()` function. That function should not have any side effects (such as plots popping up in the wrong place), but it does sometimes have them when run in R Studio. cowplot uses that function throughout to generate the various effects it creates, and there's really no way around it. In any case, it's not something I can actually fix in cowplot.

**Comment by AliciaSchep** [comment] 2017-11-11 07:07
thanks for explanation, makes sense that it is not fixable on cowplot end.  And thanks for making such a useful (& delightful) package!

**Comment by roelj** [comment] 2017-12-07 14:26
First of all, thanks for this package.  It's really nice.

Secondly, sorry to bring up an old issue, but could it be that this is not only RStudio related, but more related to `knitr` and `Sweave`? I'm experiencing a similar problem when building a Sweave vignette.  The build fails because a plot created with `plot_grid` is empty.

When I run the commands of the vignette manually in an R prompt, it works fine.

The build error occurs when I just run:
```
R CMD build <package-directory>
```

(not in RStudio)

It seems to only happen when using Bioconductor's development environment (R 3.5.0, and the development versions of Bioconductor packages).

Running the build command on a stable version of R simply works.

Thanks for your time.

**Comment by clauswilke** [comment] 2017-12-07 15:29
If `R CMD build` fails with the current development version of R then I think it's an R bug and should be reported there. R graphics devices are quite buggy and don't always do what they're supposed to. I'm only using the published APIs, so there's little I can do to work around these issues.

**Comment by roelj** [comment] 2017-12-07 16:09
Thanks @clauswilke for your quick response.
That there's not much you can do about it was already clear to me. :)

The following work-around works for me (in Sweave):
```
<<pdf_device_prep2, echo=FALSE, results=hide>>=
    grDevices::pdf(NULL)
@

<<function_returning_a_cowplot_generated_plot>>=
...
@

<<pdf_device_prep3, echo=FALSE, results=hide>>=
    grDevices::dev.off()
@
```

So that's basically what you already did in commit: https://github.com/wilkelab/cowplot/commit/89b795c0ebea57bed556310c935f0e6c728caf4e.

I am looking forward to the next `cowplot` release.

**Comment by clauswilke** [comment] 2017-12-07 17:00
Could you verify that things work as expected with the current github version of cowplot?

**Comment by clauswilke** [comment] 2017-12-09 23:07
I made various changes to the package that should reduce the likelihood of plots not printing or other weird effects. Could you check with the current version on github?

And while you're at it, could you see if you get any unexpected results or problems with `ggsave` or `save_plot`? I made some modification there also that should make things safer but may have caused unexpected problems.

**Comment by stefanocoretta** [comment] 2017-12-10 01:39
I tested the development version and it seems to me it's working fine now. No blank plots with .Rmd and `knitr`. I was getting blank plots before.

    > sessionInfo()
    R version 3.4.3 (2017-11-30)
    Platform: x86_64-apple-darwin15.6.0 (64-bit) 
    Running under: macOS High Sierra 10.13.1

    other attached packages:
    [1] cowplot_0.9.2     tidymv_1.2.0      itsadug_2.3      
    [4] plotfunctions_1.3 mgcv_1.8-22       nlme_3.1-131     
    [7] forcats_0.2.0     stringr_1.2.0     dplyr_0.7.4       
    [10] purrr_0.2.4       readr_1.1.1       tidyr_0.7.2      
    [13] tibble_1.3.4      ggplot2_2.2.1     tidyverse_1.2.1

**Comment by clauswilke** [comment] 2017-12-10 03:01
Ok, I'm closing this issue. Please reopen if the problem crops up again.

**Closed by clauswilke** 2017-12-10 03:01 UTC

**Comment by roelj** [comment] 2017-12-11 10:09
I'm late to the party, but I can also confirm that the development version works fine for me.  May I suggest to release a new version soon?
