### ISSUE TITLE
Using switch_axis_position() with facet_grid()

### ISSUE THREAD

**Issue by DanielleQuinn** [wilkelab/cowplot#20] opened 2015-12-21 22:50 UTC
I would like to switch the position of the y axis to the right hand side of my plot using

ggdraw(switch_axis_position(p1, axis = 'y'))

However, my plot is facetted using facet_grid, and so I get the error "Error in switch_yaxis_position(gt, theme, keep.y):  Can only switch axes on plots with exactly one panel."

Is there any way to work around this? Just for clarification, I'd like my y axis to be on the far right hand side of my facetted plot.. Thank you!

**Comment by clauswilke** [comment] 2015-12-22 18:46
The problem is that `switch_axis_position` uses a dirty hack to do what it does, and that hack is difficult to generalize for facetted plots. In particular, while it's probably not that hard to generalize it for *a specific faceted plot*, it will be difficult to write code that works with *any faceted plot.*

The workaround would be to take the [code in this file](https://github.com/wilkelab/cowplot/blob/master/R/switch_axis.R) and modify it so it works with your plot. Specifically, in lines 36-41, you need to identify the correct plot panel to use as a reference point. This may or may not be easy. Depends on how much you know about gtables, and probably also on the layout of your faceted plot.

**Comment by DanielleQuinn** [comment] 2015-12-28 18:17
Ok, thanks! I have only had a few moments to explore the code but I see what you have in mind - I have some airport sitting time coming up, looking forward to tackling this :)

**Comment by clauswilke** [comment] 2016-02-29 04:28
Closing this issue because I'm not expecting that I'll implement a general solution soon. Ideally, this would be addressed directly in ggplot2 anyways.

**Closed by clauswilke** 2016-02-29 04:28 UTC
