### ISSUE TITLE
Axis label justification goes bananas after `switch_axis_position` for `angle = 90`

### ISSUE THREAD

**Issue by Ax3man** [wilkelab/cowplot#25] opened 2016-02-17 18:54 UTC
While answering [a question on stackoverflow](http://stackoverflow.com/questions/35463877/ggplot-left-aligned-x-axis-labels-when-using-cowplot-to-flip-x-axis/35465052#35465052) I found that the justification for the axis labels seems to bug out if the angle is 90 degrees.

A simple (hackish) fix is to add a small amount to the degrees.

Example:
```
library(reshape2)
library(ggplot2)
library(cowplot)

# some toy data
set.seed(1)
mydata <- mtcars[, c(1, 3, 4, 5, 6, 7)]

# to show difference in justification better, make names of unequal length 
names(mydata) = paste0(sample(c("mtcars_", ""), 6, replace = TRUE), names(mydata))
cormat <- round(cor(mydata), 2)

melted_cormat <- melt(cormat)
head(melted_cormat)


plot <- ggplot(data = melted_cormat, aes(x=Var1, y=Var2, fill=value)) + 
        geom_tile() +
        theme_bw(base_size=20) + xlab("") + ylab("") +
        theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 0.5))
ggdraw(switch_axis_position(plot, 'x'))
```
This gives weird labels (you can mess around with `vjust` and `hjust`).

But this version gives the desired result:

```
plot <- ggplot(data = melted_cormat, aes(x=Var1, y=Var2, fill=value)) + 
  geom_tile() + theme_bw(base_size=20) + xlab("") + ylab("")+
  theme(axis.text.x=element_text(angle=90 + 1e-09, hjust = 0, vjust=1)) +
  coord_equal(expand = 0)
ggdraw(switch_axis_position(plot, 'x'))
```

Thanks for a great package!

**Comment by Ax3man** [comment] 2016-02-17 19:04
Centering them on the tick marks seems impossible altogether.

**Comment by clauswilke** [comment] 2016-02-17 19:23
Yes. I'm pretty sure this is a bug in ggplot2 or grid. Similar problems arise without switching the axis position, correct?

**Comment by Ax3man** [comment] 2016-02-17 20:11
Nope! See this example:

```
ggplot(data = melted_cormat, aes(x=Var1, y=Var2, fill=value)) + 
  geom_tile() + theme_bw(base_size=20) +  xlab("")+ylab("")+
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust=0.5)) +
  coord_equal(expand = 0)
```
Here the alignment seems fine.

**Comment by clauswilke** [comment] 2016-02-17 21:56
Ok, I get it now. It used to be that ggplot would simply ignore hjust and vjust when labels were rotated 90 degrees, but that seems to be fixed now. The problem is indeed the reversion of the axis. There is no generic code to invert a grid object, it's just a lot of manual fiddling. 

If you look at lines 12, 13 and 28, 29 [here,](https://github.com/wilkelab/cowplot/blob/master/R/switch_axis.R) you can see how I'm inverting the hjust/vjust value and the x/y coordinate. To work with rotations, maybe we need to invert both hjust and vjust and x and y in all cases.

I don't like special-casing this so it works with 90 degrees. There must be a general transform that can be done. I don't think I'll have time to look into this any time soon, but if you want to investigate, those are the lines that will need to be changed.

**Comment by Ax3man** [comment] 2016-02-29 08:17
As far as I can tell, also switching `x` and `y` messes things up.

### Continuous axes
Here is the first example from the vignette with only the current merge:
```
theme_set(theme_cowplot(font_size=12)) # reduce default font size
p1 <- ggplot(mtcars, aes(mpg, disp)) + geom_line(colour = "blue")
ggdraw(switch_axis_position(p1 + theme_gray(), axis = 'y'))
```
![image](https://cloud.githubusercontent.com/assets/15309336/13388943/788f8664-dec4-11e5-9ec5-7229e2eec478.png)

Here is the same plot with also `x` and `y` reversed, and now the labels are off the tickmarks:
![image](https://cloud.githubusercontent.com/assets/15309336/13388940/71e7630e-dec4-11e5-802e-52802c6118ae.png)

### Categorical axes
Another plot from the vignette:
```
p2 <- ggplot(diamonds, aes(clarity, fill = cut)) + geom_bar() +
  theme(axis.text.x = element_text(angle=70, vjust=0.5))
ggdraw(switch_axis_position(p2, axis = 'x'))
```
![image](https://cloud.githubusercontent.com/assets/15309336/13388993/fce2500e-dec4-11e5-88f7-4babe983f5b9.png)

If we also reverse coordinates, the axes labels get reversed!
![image](https://cloud.githubusercontent.com/assets/15309336/13389005/135bf060-dec5-11e5-9cfd-48d49f872f8a.png)

Only reversing both justifications seems to work alright. Hope this helps!

**Comment by clauswilke** [comment] 2016-03-06 17:51
This is on CRAN now.

**Closed** 2016-03-06 17:51 UTC
