### ISSUE TITLE
Decreasing the space between plots in plot_grid?

### ISSUE THREAD

**Issue by kendonB** [wilkelab/cowplot#31] opened 2016-03-11 16:46 UTC
I've tried the reverse of the solutions suggested in #11, and the plots end up with parts cut off. Thanks in advance!

**Comment by clauswilke** [comment] 2016-03-11 18:15
I will need a reproducible code example to understand what the issue is.

**Comment by clauswilke** [comment] 2016-04-20 00:27
I'm closing this because there isn't sufficient information here to understand what the issue is.

**Closed by clauswilke** 2016-04-20 00:27 UTC

**Comment by kendonB** [comment] 2017-04-08 21:27
Apologies for missing explaining this earlier. Suppose I have a grid:

``` r
library(ggplot2)
library(cowplot)
p1 <- qplot(1:10, 1:10)
p2 <- qplot(1:10, (1:10)^2)
# simple grid
plot_grid(p1, p2)
```

![](http://i.imgur.com/WHkdwMp.png)

I would like to squish them closer together. Is this possible in cowplot?

**Comment by kendonB** [comment] 2017-04-08 21:29
See, for example:
![](http://i.imgur.com/ynK5wPk.png)

**Comment by kendonB** [comment] 2017-04-08 21:50
Worked it out. For future googlers, ``plot_grid`` doesn't add space; it simply uses the spacing already in the plots, which you can remove using ``theme(plot.margin = unit(c(0, 0, 0, 0), "cm"))``.

``` r
library(ggplot2)
library(cowplot)
p1 <- qplot(1:10, 1:10) + theme(plot.margin = unit(c(0, 0, 0, 0), "cm"))
p2 <- qplot(1:10, (1:10)^2) + theme(plot.margin = unit(c(0, 0, 0, 0), "cm"))
plot_grid(p1, p2, p1, p2, p1, p2, p1, p2, p1, p2, p1, p2)
```

![](http://i.imgur.com/W1QNYoy.png)

**Comment by clauswilke** [comment] 2017-04-08 22:42
Yes, that's how it works. Thanks for posting a clear example solution, this question comes up quite frequently.

**Comment by eipi10** [comment] 2017-05-09 18:54
Klaus, 

It seems like the approach above doesn't work when the axis labels and titles take up different amounts of space in different panels or when you want to get rid of the axis titles and labels in some panels but not others.   

A reproducible example is below. It is based on the idea that sometimes you want a faceted plot, but you want to customize each facet in ways that are not possible with "regular" faceting. So, instead, you split the data frame by the desired faceting column, create a separate plot for each "facet", and then lay the plots out together with `plot_grid` as if they had been faceted (see, for example, [this SO answer](http://stackoverflow.com/questions/43875030/manually-order-x-axis-labels-within-each-facet-in-ggplot/43876602#43876602)). 

It would be nice if there were a way to directly control the space between panels in `plot_grid`, even in the case I discuss below. If this is already possible, and my examples are based on a misunderstanding, please let me know.

Thanks,
Joel


Example 1: We create separate plots. Then we remove the y-axis titles, labels, and ticks from all but the plot that will be left-most when we lay them out. We set the left margin of all but the left-most plot to -1 cm. But note in the image that even though we got rid of the left margin on five of the six panels, `plot_grid` seems to leave space between all the plots as if it were allowing for the width of y-axis title, labels, and ticks in the left-most plot.

```
library(tidyverse)
library(cowplot)

# Create list of plots
plist = split(mtcars, mtcars$carb) %>%  
  map(~ .x %>% group_by(carb) %>%
        ggplot(aes(x = mpg, y = wt)) + 
         geom_point())

# Remove y-axis labels, title, and ticks from all but the left-most plot
plist[2:length(plist)] = plist[2:length(plist)] %>% 
  map(~ .x + theme(axis.text.y=element_blank(),
                   axis.title.y=element_blank(),
                   axis.ticks.y=element_blank(),
                   plot.margin=margin(l=-1, unit="cm"))) 

plot_grid(plotlist=plist, ncol=length(plist), align="v")
```
![rplot09](https://cloud.githubusercontent.com/assets/436817/25866691/2658edec-34ac-11e7-8692-bc8808660669.png)

Example 2: Same idea, but now we set the left margin of *all* the plots to be -1 cm. Now we get the thin margins that we want between plots, but at the expense of cutting off the title and most of the labels at the left edge of the plot. 
```
# Create a list of plots
plist = split(mtcars, mtcars$carb) %>%  
  map(~ .x %>% group_by(carb) %>%
        ggplot(aes(x = mpg, y = wt)) + 
        geom_point() +
        theme(plot.margin=margin(l=-0.8,unit="cm")))

# Remove y-axis labels, title, and ticks from all but the left-most plot
plist[2:length(plist)] = plist[2:length(plist)] %>% 
  map(~ .x + theme(axis.text.y=element_blank(),
                   axis.title.y=element_blank(),
                   axis.ticks.y=element_blank())) 

plot_grid(plotlist=plist, ncol=length(plist), align="v")
```
![rplot10](https://cloud.githubusercontent.com/assets/436817/25867086/60d41888-34ad-11e7-8f7d-d620dd8d9a54.png)

**Comment by clauswilke** [comment] 2017-05-09 21:02
The trick is to extract the x axis label from a plot and add it as a separate column in a plot that otherwise looks like your Example 2. Something along the lines of the last example here: https://cran.r-project.org/web/packages/cowplot/vignettes/shared_legends.html

The code you'd need to write to extract the axis labels would be similar to the `get_legend` function, you just need to extract a different grob, probably the one called `ylab-l`:
https://github.com/wilkelab/cowplot/blob/master/R/get_legend.R

**Comment by luize-bg** [comment] 2018-05-15 14:34
It seems to me that when we use align="hv" and the last element of the first line is NULL the approach to making the margin of each plot smaller does not work. I'm trying to approximate density plots to the top and left margin of a line with scater plots (as eipi10 commented) and let the axes of the plots allingned. But when I use the (plot.margin) command I really do not have succees in making the plots closer togheter.

**Comment by clauswilke** [comment] 2018-05-15 14:46
For those kinds of problems I would now recommend the patchwork library. It's inherently difficult with `plot_grid()`, due to its underlying design.

**Comment by BrownAlpine** [comment] 2019-02-25 14:16
do you know why as I add rows with `plot_grid` the size of my plots shrinks to the point where they become unreadable? (let's say I want to print 6 plots `ncol=6, nrow=1`  and it works fine. Then I add 24 other plots to get to `ncol=6, nrow=5` and it does not work anymore). I posted it [here](https://www.reddit.com/r/rstats/comments/aukouj/cowplot_plot_grid_scales_down_size_of_plots/)

**Comment by yewero** [comment] 2021-04-21 08:22
@kendonB Here is a solution (by Valentin):
https://stackoverflow.com/questions/41834093/decrease-margins-between-plots-when-using-cowplot
```
plot5 <- plot_grid(plot1, NULL, plot2, rel_widths = c(1, -0.1, 1), align = "hv",
                   labels = c("A", "B"), nrow = 1)
plot5
```
