### ISSUE TITLE
changing font causes spacing issues for legend

### ISSUE THREAD

**Issue by steveharoz** [wilkelab/cowplot#73] opened 2017-08-28 23:32 UTC
Test case:

```
library(extrafont)
#font_import() #<-- run once, takes a long time
loadfonts(device="win", quiet=TRUE)

plotTemp = 
  ggplot(mtcars) +
  aes(x=cyl, fill=paste(cyl, "cylinders")) +
  geom_bar() +
  theme(text = element_text(family="Arial")) # pick a font on your system
```

The basic plot works fine:
```
plotTemp
```
![image](https://user-images.githubusercontent.com/2257540/29797827-09bc2814-8c1f-11e7-8480-8c3bc212a6c0.png)

Using `plot_grid` clips the legend
```
cowplot::plot_grid(plotTemp, plotTemp, ncol=1, align="v")
```
![image](https://user-images.githubusercontent.com/2257540/29797813-f86c3860-8c1e-11e7-9fab-de292e58e818.png)

Also, there's a weird issue when legend.position = "top"
```
plotTemp = plotTemp + theme(legend.position = "top")
cowplot::plot_grid(plotTemp, plotTemp, ncol=1, align="v")
```
![image](https://user-images.githubusercontent.com/2257540/29797855-27b64eb2-8c1f-11e7-84be-816ee67106d5.png)

**Comment by clauswilke** [comment] 2017-08-29 01:04
I doubt the problem is cowplot. Can you try the following:
```
g <- ggplot2::ggplotGrob(plotTemp)
grid::grid.draw(g)
```
and see if either of the issues (cut-off or mangled legends) occur? I suspect they will.

**Comment by steveharoz** [comment] 2017-08-29 01:08
That works fine 
![image](https://user-images.githubusercontent.com/2257540/29799908-9cf3599c-8c2c-11e7-90a5-64b9a82c5d29.png)

**Comment by clauswilke** [comment] 2017-08-29 01:18
Ok. Different test: In `plot_grid`, does it break even if you don't use `align = "v"`?

**Comment by steveharoz** [comment] 2017-08-29 01:21
Yeah, that breaks
```
cowplot::plot_grid(plotTemp, plotTemp, ncol=1)
```
![image](https://user-images.githubusercontent.com/2257540/29800225-6ec4ff38-8c2e-11e7-8dc7-7382b5a888ea.png)

**Comment by clauswilke** [comment] 2017-08-29 01:27
Another question: How do you generate these figures? R graphics sometimes are cut off when shown in a window, until you resize the window. I'd prefer to talk about code that saves a figure as pdf or png, since that's more reproducible.

**Comment by steveharoz** [comment] 2017-08-29 01:36
I originally encountered the problem when saving to a file via `CairoPNG`. The screenshot in this post were from the RStudio plot popout. However, the issue still happens when saving to a file via `ggsave()` with default settings.
![cowplot](https://user-images.githubusercontent.com/2257540/29800605-96a1b22e-8c30-11e7-893f-1a3fc5c7de42.png)

**Comment by clauswilke** [comment] 2017-08-29 01:39
Ok, this will require some further digging. I can't look into this now but may get back to it at some point.

**Comment by luizaantunes** [comment] 2018-03-09 16:12
Same issue, used:  family = "Trebuchet MS" on plot axis and tittles. 
Tried to fix by adding device=cairo_pdf in ggsave(), it corrected ggsave() but made the cowplot plot_grid() even worse.

**Comment by clauswilke** [comment] 2018-03-16 18:47
I can't debug this on windows, because I don't have windows, but from reading the documentation I suspect that `loadfonts(device="win", quiet=TRUE)` may be the culprit. cowplot always uses a pdf device at some point, even if the final output is not pdf. So to use additional fonts, you will have to register the fonts with the pdf device as well.

**Comment by clauswilke** [comment] 2018-03-16 20:34
I committed a fix. Can you check it? The following code works for me. `library(extrafont)` should not be needed, but you do need Cairo.

```{r}
library(Cairo)
library(cowplot)

plotTemp = 
  ggplot(mtcars) +
  aes(x=cyl, fill=paste(cyl, "cylinders")) +
  geom_bar() +
  theme(text = element_text(family="Trebuchet MS")) # pick a font on your system

cowplot::plot_grid(plotTemp, plotTemp, ncol=1, align="v")
```
<img width="732" alt="screen shot 2018-03-16 at 3 32 00 pm" src="https://user-images.githubusercontent.com/4210929/37543394-6ca0b5a0-292f-11e8-9a2f-dcce71348812.png">


```{r}
plotTemp = plotTemp + theme(legend.position = "top")
cowplot::plot_grid(plotTemp, plotTemp, ncol=1, align="v")
```
<img width="732" alt="screen shot 2018-03-16 at 3 32 09 pm" src="https://user-images.githubusercontent.com/4210929/37543401-72733282-292f-11e8-9096-319e74e4479e.png">

**Comment by steveharoz** [comment] 2018-03-16 22:22
I installed the dev version `devtools::install_github("wilkelab/cowplot")`

```
library(Cairo)
library(cowplot)

plotTemp = 
  ggplot(mtcars) +
  aes(x=cyl, fill=paste(cyl, "cylinders")) +
  geom_bar() +
  theme(text = element_text(family="Comic Sans MS")) # distinctive font
```

**The RStudio viewer can't use the correct fonts**
```
cowplot::plot_grid(plotTemp, plotTemp, ncol=1, align="v")
```
![image](https://user-images.githubusercontent.com/2257540/37547025-b82002a2-296f-11e8-88c8-191b46f02e8a.png)
```
There were 50 or more warnings (use warnings() to see the first 50)
> warnings()
Warning messages:
  1: In grid.Call(C_textBounds, as.graphicsAnnot(x$label),  ... :
                    font family not found in Windows font database
```

**Using the Cairo viewer works!**
```
CairoWin()
cowplot::plot_grid(plotTemp, plotTemp, ncol=1, align="v")
```
![image](https://user-images.githubusercontent.com/2257540/37547114-11703854-2970-11e8-880f-ea76f5483599.png)
```
plotTemp = plotTemp + theme(legend.position = "top")
cowplot::plot_grid(plotTemp, plotTemp, ncol=1)
```
![image](https://user-images.githubusercontent.com/2257540/37547180-55a3c932-2970-11e8-92d3-9c1a82aa4ef8.png)

Using Cairo to save works too
```
Cairo(1000, 750, 'cowplottest.png', bg = 'white')
last_plot()
dev.off()
```

**So it seems that using cowplot on Windows requires using the Cairo graphics device**

**Comment by clauswilke** [comment] 2018-03-17 00:24
Thanks. There are still some subtle font metric issues that I need to resolve, but at least it's not blatantly wrong.

**Comment by clauswilke** [comment] 2018-03-17 05:40
I've done some more digging. It turns out there is no single solution that always works. The problem is that we need to open a null graphics device for some of the cowplot operations, and there is no universal null graphics device that works reliably in all circumstances. On OS X, for example, the solution I pushed earlier does not work. (Cairo is broken there. It ignores font settings.)

So, the solution is to allow the user to choose their own null device. This means you can always choose the one that works the best in your situation. Below, I show how the various null devices work in OS X, and why Cairo does not work.

```{r}
library(cowplot)

# make plot with narrow font and without margins
p <- ggplot(iris, aes(Sepal.Length, Sepal.Width, color = Species)) + 
  geom_point() + 
  theme_minimal(base_family = "Arial Narrow") + 
  theme(legend.margin = margin(0, 0, 0, 0), plot.margin = margin(0, 0, 0, 0))

# pdf null device (the default) without extrafont doesn't work
ggdraw(p)
## There were 18 warnings (use warnings() to see them)
```
![p1](https://user-images.githubusercontent.com/4210929/37552054-4e6ca976-297b-11e8-80f4-8ac3c6910dd8.png)
(We see that things don't work properly because the text doesn't extend all the way to the end of the image.)

```{r}
# cairo null device gets font metrics wrong
set_null_device("cairo")
ggdraw(p)
```
![p2](https://user-images.githubusercontent.com/4210929/37552058-63564ff4-297b-11e8-9f7f-6ee227b1f0af.png)
(Same issue as before.)

```{r}
# png null device works without problems
set_null_device("png")
ggdraw(p)
```
![p3](https://user-images.githubusercontent.com/4210929/37552073-af59a0ea-297b-11e8-9223-a30879734d91.png)

```{r}
# on OS X, pdf null device with extrafont works
library(extrafont)
ggdraw(p)
```
![p4](https://user-images.githubusercontent.com/4210929/37552075-bc4be0f6-297b-11e8-8c65-f2c81b75c26b.png)

```{r}
# on OS X, jpeg null device also works
jpeg_null_device <- function() {jpeg(filename = "jpeg_null_plot.jpg")}
set_null_device(jpeg_null_device)
ggdraw(p)
```
![p5](https://user-images.githubusercontent.com/4210929/37552049-330a389c-297b-11e8-8e1a-490c0eb99c79.png)

**Comment by steveharoz** [comment] 2018-03-17 07:31
Just updated. It's behaving differently on my windows computer.

```
library(cowplot)
# make plot with specific font and without margins
p <- ggplot(iris, aes(Sepal.Length, Sepal.Width, color = Species)) + 
  geom_point() + 
  theme_minimal(base_size = 20, base_family = "Comic Sans MS") + 
  theme(legend.margin = margin(0, 0, 0, 0), plot.margin = margin(0, 0, 0, 0))
```

```
# pdf null device (the default) without extrafont doesn't work
ggdraw(p)
## There were 20 warnings (use warnings() to see them)
```

```
# Note that cairo null device gives me warnings (unlike on your computer)
set_null_device("cairo")
ggdraw(p)
## Warning messages:
##   1: In grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y,  :
##                     font family not found in Windows font database
```

```
# extrafont and cairo null device works!
library(extrafont)
ggdraw(p)
ggdraw(p + theme(legend.position = "top"))
```
![image](https://user-images.githubusercontent.com/2257540/37552816-6e17164e-29bc-11e8-83b8-b88e42038bcb.png)
![image](https://user-images.githubusercontent.com/2257540/37552822-89ec08a2-29bc-11e8-8128-cc8c103a4458.png)


```
# pdf null device messes up borders
set_null_device("pdf")
ggdraw(p)
```
![image](https://user-images.githubusercontent.com/2257540/37552825-9aaece0e-29bc-11e8-9bd8-852d21ffd284.png)

**Comment by clauswilke** [comment] 2018-05-05 22:33
Closing this issue. As far as I can tell, this works fine now. I have been using non-standard fonts for several months without problems.

**Closed by clauswilke** 2018-05-05 22:33 UTC
