### ISSUE TITLE
Blank plot when using cowplot with RNotebook

### ISSUE THREAD

**Issue by DanielReedOcean** [wilkelab/cowplot#82] opened 2017-11-30 17:31 UTC
When using `cowplot` with RNotebook an additional blank plot is created before the requested plot. For example,
````
---
title: "R Notebook"
output: html_notebook
---

```{r}
library(cowplot)
library(ggplot2)
g <- ggplot(mtcars) + geom_point(aes(mpg, hp))
plot_grid(g,g)
```
````
produces the following:
 
![capture](https://user-images.githubusercontent.com/11167566/33444987-0f9da026-d5d2-11e7-8221-098adb02f0dd.PNG)
 Note that this **doesn't** happen if the file is knitted as a `html_document` rather than `html_notebook`.

**Comment by clauswilke** [comment] 2017-11-30 17:58
Could you try the following, please? Replace this line:

```
plot_grid(g,g)
```

with these three lines:
```
grDevices::pdf(NULL)
plot_grid(g,g)
grDevices::dev.off()
```
and see if this prevents the problem. If it does, we may be able to put this workaround into the `plot_grid()` function.

**Comment by DanielReedOcean** [comment] 2017-11-30 18:01
When I do that there are no plots at all. Instead, I get the following:

```
null device 
          1 
```

**Comment by DanielReedOcean** [comment] 2017-11-30 18:13
Boom! No blank plot.
![capture2](https://user-images.githubusercontent.com/11167566/33447055-634a344a-d5d8-11e7-9a45-a3c87c958312.PNG)

**Comment by clauswilke** [comment] 2017-11-30 18:19
Yeah, I think I always need to open a null pdf device when converting plots, not just when one is already open. The problem is I vaguely remember that somebody objected to that. I think in some cases the pdf device is not available. I may just make this change and see if somebody complains.

**Comment by DanielReedOcean** [comment] 2017-11-30 18:23
Okay, thanks for getting this figured out so quickly.

**Comment by clauswilke** [comment] 2017-11-30 18:30
I committed a fix that should resolve the issue for you and will hopefully not introduce other pains. Can you install the github version of cowplot and see if things work now?

**Comment by DanielReedOcean** [comment] 2017-11-30 18:52
It looks great! Thanks.

**Comment by clauswilke** [comment] 2017-12-09 22:38
Closing this. It seems to work now.

**Closed by clauswilke** 2017-12-09 22:38 UTC
